# Generated by Django 3.2.9 on 2023-02-24 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('work_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('work', models.ManyToManyField(to='signup.Work')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
